name: CI

on:
  push:
    branches:
      - main

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt
          pip install pytest

      # Debugging output
      - name: Check current directory and list files after pipeline
        run: |
          pwd
          ls -la

      - name: Set execute permissions and run tests
        run: |
          chmod +x project/tests.sh
          ./project/tests.sh

    

   
